<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.img.backend.mobile.tamcapp.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://service.img.backend.mobile.tamcapp.com/" name="ImageService">
  <wsp:UsingPolicy wssutil:Required="true"/>
  <wsp:Policy xmlns:wssutil="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
              wssutil:Id="Mtom.xml" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
    <ns1:OptimizedMimeSerialization xmlns:ns1="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"/>
  </wsp:Policy>
  <types>
    <xsd:schema>
      <xsd:import namespace="http://service.img.backend.mobile.tamcapp.com/" schemaLocation="ImageServicePort1.xsd"/>
    </xsd:schema>
  </types>
  <message name="saveImage">
    <part name="parameters" element="tns:saveImage"/>
  </message>
  <portType name="ImageService">
    <operation name="saveImage">
      <input message="tns:saveImage"/>
    </operation>
  </portType>
  <binding name="ImageServicePortBinding" type="tns:ImageService">
    <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#Mtom.xml" required="false"/>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="saveImage">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="ImageService">
    <port name="ImageServicePort" binding="tns:ImageServicePortBinding">
      <soap:address location="http://localhost:7101/TAMCAPP-att-ViewController-context-root/ImageWsDcService"/>
    </port>
  </service>
</definitions>